server {
    listen 80;
    server_name 2b2t-th.org www.2b2t-th.org;
    return 301 https://www.2b2t-th.org$request_uri;
}

server {
    listen 443 ssl;
    server_name 2b2t-th.org;
    ssl_certificate /etc/letsencrypt/live/2b2t-th.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/2b2t-th.org/privkey.pem;
    return 301 https://www.2b2t-th.org$request_uri;
}

server {
    listen 443 ssl;
    server_name www.2b2t-th.org;
    ssl_certificate /etc/letsencrypt/live/2b2t-th.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/2b2t-th.org/privkey.pem;

    location / {
        proxy_pass http://web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}